/* JS is generated by ai(ChatGPT). */

document.addEventListener('DOMContentLoaded', () => {
    document.querySelector('select').addEventListener('change', e => e.target.value !== "selectcity" && alert(`You selected: ${e.target.value}`));
    document.querySelector('main p')?.classList.add('animate');
    document.querySelector('button')?.addEventListener('click', () => document.querySelector('.main-collections').scrollIntoView({ behavior: 'smooth' }));
    document.querySelector('.suggetion-city .sugg-city:last-child button')?.addEventListener('click', () => alert('Redirecting to more suggestions...'));
    ['email', 'phone'].forEach(id => document.getElementById(id)?.addEventListener('change', () => document.querySelector('.download-app input[type="text"]').placeholder = id === 'email' ? 'Enter your email' : 'Enter your phone number'));
    document.querySelector('.download-app button')?.addEventListener('click', () => alert('We will send you a download link!'));
    document.querySelectorAll('.main-feature .cta-btn').forEach(btn => btn.addEventListener('click', () => alert('Redirecting to order page...')));
    document.querySelectorAll('footer a').forEach(link => { link.addEventListener('mouseenter', () => link.style.textDecoration = 'underline'); link.addEventListener('mouseleave', () => link.style.textDecoration = 'none'); });
});
